name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  
          REPOSITORY: joyson-fernandes/joyson-fernandes
          CREDLY_USER: joyson-fernandes # optional, but default will use the same from github
          BADGE_SIZE: 100
          NUMBER_LAST_BADGES: 30

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Constrain badge size
        run: |
          sed -i -E '/START_SECTION:badges/,/END_SECTION:badges/ s#^\[!\[([^]]*)\]\(([^)]*)\)\]\(([^)]*)\)$#<a href="\3"><img src="\2" alt="\1" width="80" height="80"></a>#' README.md
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "Constrain Credly badge size"
            git push
          fi
